# Generated by Django 4.1.5 on 2023-01-03 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('familia', '0003_family_delete_products'),
    ]

    operations = [
        migrations.AddField(
            model_name='family',
            name='surname',
            field=models.CharField(default=str, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='family',
            name='name',
            field=models.CharField(max_length=80),
        ),
    ]
