# Generated by Django 4.1.5 on 2023-01-03 15:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('familia', '0004_family_surname_alter_family_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='family',
            name='surname',
        ),
    ]
